---
title: "Wild Data"
author: "Desik Somasundaram"
date: "8/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
```

## Read in the data
```{r}
mack_verts <- read_csv(here("data", "AS00601.csv"))

mack_verts <- mack_verts %>% clean_names()

```
```{r}
mc_wt_5 <- mack_verts$weight[5]
mc_length_8_20 <- mack_verts$length1[8:20]
mc_dates <- mack_verts$sampledate
```

## Salamander Subset

```{r}
mc_salamanders <- mack_verts %>%  dplyr::filter(mack_verts$species == "DITE")
```

## Make Scatter Plot

```{r}
salamander_size <- ggplot(data = mc_salamanders, aes(x = weight, y = length1)) +
  geom_point(aes(color = year), size = 1) + 
  xlab("Weight (grams)") + 
  ylab("Length (mm)") +
  labs(title = "Salamander Length vs Weight",
       subtitle = "Pacific Giant Salamanders",  
       caption = "EDI Data Portal") +
  theme_light()

salamander_size

ggsave(here("figs","salamander_size.png"))

```
## Make Trout Subset

```{r}
mc_trouts <- mack_verts %>%  dplyr::filter(mack_verts$species == "ONCL")
```

## Make Cutthroat Scatter Plot

```{r}
cutthroat_size <- ggplot(data = mc_trouts, aes(x = weight, y = length1)) +
  geom_point(aes(color = reach), size = 1) + 
  xlab("Weight (grams)") + 
  ylab("Length (mm)") +
  labs(title = "Trout Length vs Weight",
       subtitle = "Cutthroat Trout",  
       caption = "EDI Data Portal") +
  scale_color_manual(values = c("L" = "blue", "M" = "green", "U" = "yellow")) +
  facet_wrap(~reach)

cutthroat_size

ggsave(here("figs","cutthroat_size.png"), plot = cutthroat_size)

```

